# Generated by Django 4.2.7 on 2026-02-02 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('BLOOD', 'Blood Test'), ('URINE', 'Urine Test'), ('XRAY', 'X-Ray'), ('MRI', 'MRI Scan'), ('CT', 'CT Scan'), ('ECG', 'ECG'), ('ULTRASOUND', 'Ultrasound'), ('OTHER', 'Other')], max_length=20)),
                ('test_name', models.CharField(max_length=200)),
                ('test_date', models.DateField()),
                ('report_file', models.FileField(blank=True, null=True, upload_to='lab_reports/')),
                ('summary', models.TextField(blank=True, help_text='Brief summary of findings')),
                ('is_normal', models.BooleanField(default=True, help_text='Are results within normal range?')),
                ('remarks', models.TextField(blank=True, help_text="Doctor's remarks on the report")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports_ordered', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='lab_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lab Report',
                'verbose_name_plural': 'Lab Reports',
                'ordering': ['-test_date'],
            },
        ),
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(help_text='e.g., Hemoglobin, Blood Sugar', max_length=100)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text='e.g., mg/dL, g/dL', max_length=50)),
                ('normal_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('normal_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_abnormal', models.BooleanField(default=False)),
                ('lab_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='lab_reports.labreport')),
            ],
            options={
                'verbose_name': 'Lab Test Parameter',
                'verbose_name_plural': 'Lab Test Parameters',
                'ordering': ['parameter_name'],
            },
        ),
    ]
